"""Constants for Data Inspector Widget"""

# Mapping documentation for standardized categorical columns
CATEGORICAL_MAPPINGS = {
    'gender': 'Numeric codes (1/2/3) mapped to Male/Female/Other',
    'race': 'Numeric codes (1-6) mapped to descriptive race categories with "Race:" prefix',
    'survival_status_lfu': 'Numeric codes (0/1/2) mapped to Alive/Deceased/Lost to FU',
    'dx_cart': 'Numeric codes (1-4) mapped to Lymphoma/ALL/MM/Other',
    'cart_product': 'Numeric codes (1-6) mapped to CAR-T product names (Tisa-cel/Axi-cel/etc.)',
    'cat_cause_death': 'Numeric codes (1/2) and text variants mapped to "Disease progression" or "NRM"',
    'performance_status': 'Numeric ECOG scores (0-3) mapped to descriptive labels (e.g., "ECOG 0: Fully active")',
    'cns_involvement': 'Binary values (0/1, yes/no) standardized to Yes/No',
    'cns_status': 'Binary values (0/1, prior/active) standardized to Prior/Active',
    'cns_involvement_level': 'Numeric codes (1-3) and variants mapped to CNS-1/CNS-2/CNS-3',
    'bridging_tx': 'Case-insensitive yes/no variants standardized to Yes/No',
    'bridging_type': 'Numeric codes (1-4) and text variants (chemo/radiation/etc.) mapped to 4 categories: Steroids, Chemo-based regimen, Radiation therapy, Other',
    'burden_before_cart': 'Numeric code (0) and text variants (bulky/none) mapped to "No burden" or "Bulky"',
    'best_response': 'All response variants (14 types including MM-specific MRD/sCR/VGPR) consolidated to 5 standard categories: Complete Response, Partial Response, Stable Disease, Progressive Disease, Inevaluable',
    'cart_response_category_D30': 'Same as best_response - all variants mapped to 5 standard response categories',
    'cart_response_90_days': 'Same as best_response - all variants mapped to 5 standard response categories',
    'cart_response_6_mos': 'Same as best_response - all variants mapped to 5 standard response categories',
    'cart_response_1_yr': 'Same as best_response - all variants mapped to 5 standard response categories',
    'relapse_or_progression': 'Case-insensitive yes/no variants standardized to Yes/No',
    'cd19_post_relapse': 'Case-insensitive variants (positive/negative/unknown) standardized to Positive/Negative/Unknown',
    'ethnicity': 'Numeric codes (0/0.0/1/1.0) and text variants mapped to "Not Hispanic or Latino" or "Hispanic or Latino"',
    'lymphodep_regimen': 'Abbreviated form "Flu/Cy" consolidated to "Fludarabine, Cyclophosphamide"',
    'icans': 'Mixed numeric (0/1, 0.0/1.0) and text (yes/no) standardized to Yes/No',
    'iec-hs': 'Mixed numeric (0/1, 0.0/1.0) and text (yes/no) standardized to Yes/No',
    'icu_admission': 'Mixed numeric (0/1, 0.0/1.0) and text (yes/no) standardized to Yes/No',
    'prbc_infusion': 'Mixed numeric (0/1, 0.0/1.0) and text (yes/no) standardized to Yes/No',
    'plt_transfusion': 'Mixed numeric (0/1, 0.0/1.0) and text (yes/no) standardized to Yes/No',
    'infection_30days': 'Mixed numeric (0/1, 0.0/1.0) and text (yes/no) standardized to Yes/No',
    'pt_transfusion': 'Mixed numeric (0/1, 0.0/1.0) and text (yes/no) standardized to Yes/No',
    'infection_type_30days': 'Numeric prefixes removed (e.g., "1, Bacterial" → "Bacterial"), case-standardized (bacterial → Bacterial), specific types preserved',
    'infection_type_100_days': 'Numeric prefixes removed (e.g., "2, Viral" → "Viral"), case-standardized (viral → Viral), specific types preserved',
}
